<footer>
    <p>
        &copy; 2025 The Merge Masters. All Rights Reserved.<br>
        Disclaimer: Tolstra is a fictional project created for educational purposes. It is not affiliated with,
        endorsed by, or associated with Telstra Corporation Limited.
    </p>
    <p>
        <!-- TODO: make the link point to the new Jira project once it's created -->
        <a href=""
            target="_blank" title="Merge Masters Jira">Jira Project (TODO)</a>
        &nbsp;
        <a href="https://github.com/AshKmo/cos10026-part2" target="_blank" title="AshKmo/cos10026-part2 on GitHub">Site
            GitHub repository</a>
        &nbsp;
        <a href="mailto:info@tolstra.com.au" title="info@tolstra.com.au">Contact Us</a>
    </p>
</footer>