<!-- this file contains a few common meta tags that should be included into the <head> tag of all regular pages -->

<!-- Set the charset to UTF-8 -->
<meta charset="UTF-8">

<!-- Set page authors -->
<meta name="author" content="Ash, Hayden, Max, Tim">

<!-- Set the page width to follow the device width and set the initial zoom scale to 1.0 -->
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- Import the main stylesheet -->
<link rel="stylesheet" type="text/css" href="styles/styles.php">

<!-- Set the favicon (favicon made by ChatGPT) -->
<link rel="icon" type="image/x-icon" href="images/favicon.png">